version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bc-landlord-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bc-landlord-manager
    networks:
      - bc-landlord-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bc-landlord-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/bc-landlord-manager
      - JWT_SECRET=${JWT_SECRET:-default-secret-change-in-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - bc-landlord-network
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bc-landlord-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - bc-landlord-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  bc-landlord-network:
    driver: bridge
